FROM nginx:1.15.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

#mkdir cria pasta se nao existir #touch cria um arquivo em branco
RUN mkdir /var/www/html -p && touch /var/www/html/index.php